In [1]:
import numpy as np

In [2]:
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([7,6,9])

print(matrix)
print(vector)

[[1 2 3]
 [4 5 6]]
[7 6 9]


In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
vector

array([7, 6, 9])

In [8]:
print(matrix.shape)
print(vector.shape)

(2, 3)
(3,)


In [13]:
matrix + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
vector + 3

array([10,  9, 12])

In [18]:
a=np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [5,6],
    [7,8]
])

In [21]:
print(f"a+b=\n{a+b}")
print(f"a*b=\n{a*b}")

a+b=
[[ 6  8]
 [10 12]]
a*b=
[[ 5 12]
 [21 32]]


# Matrix-Matrix DOT Multiplication

In [22]:
a.dot(b)


array([[19, 22],
       [43, 50]])

# Transpose Matrix

In [ ]:
c=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Negetive Matrix

In [28]:
print(-c)
-c

[[-1 -2 -3]
 [-4 -5 -6]]


array([[-1, -2, -3],
       [-4, -5, -6]])

# Inverse Matrix

In [32]:
d = np.array([
    [0.20, 0.25, 0.75],
    [0.10, 0.02, 0.025],
    [0.20, 0.75, 0.10]
])



In [33]:
print(d.shape)
print(np.linalg.inv(d))

(3, 3)
[[-0.34429599 11.04830421 -0.17985612]
 [-0.10277492 -2.672148    1.43884892]
 [ 1.45940391 -2.05549846 -0.43165468]]


In [36]:
d = np.array([
    [67,19,21],
    [39,13,14],
    [81,24,26]
])


determine=np.linalg.det(d)

In [37]:
print(determine)

-42.999999999999865


# eigen value and vector

In [40]:
M=np.array([
    [1,2,3],
    [4,5,6],
    [2,9,5]
])

In [45]:
eigvalue,eigvector=np.linalg.eig(M)
print(f"Eigen Value : {eigvalue}")
print(f"Eigen Vector : {eigvector}")

Eigen Value : [13.60405743+0.j         -1.30202872+0.85467427j -1.30202872-0.85467427j]
Eigen Vector : [[ 0.27290581+0.j          0.48002115+0.29391132j  0.48002115-0.29391132j]
 [ 0.63242049+0.j          0.39363982-0.13316529j  0.39363982+0.13316529j]
 [ 0.72495983+0.j         -0.71450019+0.j         -0.71450019-0.j        ]]
